language: php
php:
- 5.5
- 5.6
- 7
env:
- TYPO3_VERSION=^7.6.0 COVERAGE=0
matrix:
  fast_finish: true
  exclude:
    - php: 5.6
      env: TYPO3_VERSION=^7.6.0 COVERAGE=0
  include:
    - php: 5.6
      env: TYPO3_VERSION=^7.6.0 COVERAGE=1
    - php: 7
      env: TYPO3_VERSION=^8.1.0 COVERAGE=0
    - php: 7
      env: TYPO3_VERSION=dev-master COVERAGE=0
  allow_failures:
    - env: TYPO3_VERSION=dev-master COVERAGE=0
sudo: false
cache:
  directories:
  - "$HOME/.composer/cache"
before_install:
- |
  if [[ "$COVERAGE" == "0" ]]; then
    phpenv config-rm xdebug.ini
  fi;
- composer self-update
- composer --version
- if [ "$GITHUB_COMPOSER_AUTH" ]; then composer config -g github-oauth.github.com
  $GITHUB_COMPOSER_AUTH; fi
before_script:
- composer require typo3/cms=$TYPO3_VERSION
- export TYPO3_PATH_WEB="$PWD/.Build/Web"
script:
- |
  echo; echo "Running unit tests";
  if [[ "$COVERAGE" == "1" ]]; then
    .Build/bin/phpunit -c .Build/vendor/typo3/cms/typo3/sysext/core/Build/UnitTests.xml --coverage-clover=.Build/unittest-coverage.clover Tests/Unit/
  else
    .Build/bin/phpunit -c .Build/vendor/typo3/cms/typo3/sysext/core/Build/UnitTests.xml Tests/Unit/
  fi;
- |
  echo; echo "Executing PHP mess detector"; .Build/bin/phpmd Classes/ text cleancode,codesize,controversial,design,naming || true
- |
  echo; echo "Executing PHP code sniffer"; .Build/bin/phpcs --runtime-set ignore_warnings_on_exit true --standard=PSR2 Classes/

